definitions:
  models.GetDentistsListResponse:
    properties:
      clone_name:
        type: string
      id:
        type: integer
      img:
        type: string
      info:
        type: string
      language:
        type: string
      name:
        type: string
      priority:
        type: integer
      side:
        type: string
    type: object
  models.ResponseError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/dentists/{id}:
    get:
      consumes:
      - application/json
      description: Get one dentist by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetDentistsListResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Get one dentist
      tags:
      - dentists
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
