CREATE TABLE IF NOT EXISTS "users" (
    "guid" UUID NOT NULL,
    "role" CHARACTER VARYING(64) NOT NULL,
    "firstname" CHARACTER VARYING(64) NOT NULL,
    "lastname" CHARACTER VARYING(64) NOT NULL,
    "username" CHARACTER VARYING(64) NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_guid_pkey PRIMARY KEY (guid)
);